GreptimeTeam/greptime-proto

- java/src/main/java/io/greptime/v1/Columns.java
- java/src/main/java/io/greptime/v1/Database.java
- java/src/main/java/io/greptime/v1/Ddl.java
_PLEASE DO NOT LEAVE THIS EMPTY !!!_
Please explain IN DETAIL what the changes are in this PR and why they are needed:
Forgot to generate Java code for 'dbname'.
> fix: gen code java

- proto/greptime/v1/meta/common.proto
- proto/greptime/v1/meta/heartbeat.proto
- src/v1/meta.rs
_PLEASE DO NOT LEAVE THIS EMPTY !!!_
Please explain IN DETAIL what the changes are in this PR and why they are needed:
- Add `role` field to header, 0: datanode, 1: frontend
- Change the data type of the timestamp to int64.
- Add `MailboxMessage` to Heartbeat message for RPC
> feat: rpc message based heartbeat

- src/v1/meta.rs
https://github.com/GreptimeTeam/greptimedb/pull/1555
> fix: add role paramter in meta RequestHeader::new()

- src/v1/meta.rs
This pr mainly modify no_active_datanodes error msg.
https://github.com/GreptimeTeam/greptimedb/pull/1654
> chore: modify no_active_datanodes error msg

- src/v1/meta.rs
> chore: modify not_enough_available_datanodes error msg

- src/v1.rs
> chore: pub region mod

- c++/greptime/v1/region/server.grpc.pb.cc
- c++/greptime/v1/region/server.grpc.pb.h
- c++/greptime/v1/region/server.pb.cc
- c++/greptime/v1/region/server.pb.h
- java/src/main/java/io/greptime/v1/region/Server.java
- proto/greptime/v1/region/server.proto
- Remove streaming API as not planned
- Use `Rows` in insert/delete request
> fix: minor changes to region server

- c++/greptime/v1/region/server.pb.cc
- c++/greptime/v1/region/server.pb.h
- java/src/main/java/io/greptime/v1/region/Server.java
- proto/greptime/v1/region/server.proto
Add region storage path to Create/OpenRequest, remove catalog, schema.
> feat: region storage path

- c++/greptime/v1/region/server.pb.cc
- c++/greptime/v1/region/server.pb.h
- java/src/main/java/io/greptime/v1/region/Server.java
- proto/greptime/v1/region/server.proto
This PR removes create_if_not_exists from CreateRequest
> feat: remove create_if_not_exists from region CreateRequest

- c++/greptime/v1/region/server.pb.cc
- c++/greptime/v1/region/server.pb.h
- java/src/main/java/io/greptime/v1/region/Server.java
- proto/greptime/v1/region/server.proto
Add `TruncateRequest` in region server.
> feat: add truncation request in region server

- .github/workflows/mvn_publish.yml
- java/pom.xml
_PLEASE DO NOT LEAVE THIS EMPTY !!!_
Please explain IN DETAIL what the changes are in this PR and why they are needed:
- Summarize your change (**mandatory**)
- How does this PR work? Need a brief introduction for the changed logic (optional)
- Describe clearly one logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)
> ci: publish maven artifact

- java/pom.xml
> feat: java proto v0.4.1

- java/pom.xml
> release: v0.4.3

- Cargo.toml
- proto/greptime/v1/region/server.proto
as title
for updating greptimedb's datafusion
> chore: upgrade tonic and add timezone to region request header

- .github/workflows/semantic-pr.yml
Incorrect name. Refer to https://github.com/amannn/action-semantic-pull-request/tree/v5/
> ci: fixup config pass

- .github/workflows/mvn_publish.yml
> fix: mvn publish

- c++/greptime/v1/ddl.pb.cc
- c++/greptime/v1/ddl.pb.h
- c++/greptime/v1/region/server.pb.cc
- c++/greptime/v1/region/server.pb.h
- go/greptime/v1/ddl.pb.go
- java/src/main/java/io/greptime/v1/Ddl.java
- java/src/main/java/io/greptime/v1/region/Server.java
- proto/greptime/v1/ddl.proto
- proto/greptime/v1/region/server.proto
https://github.com/GreptimeTeam/greptimedb/pull/5000
as title.
> chore: rename ChangeColumnType to ModifyColumnType

- c++/greptime/v1/index/inverted_index.pb.cc
- c++/greptime/v1/index/inverted_index.pb.h
- c++/greptime/v1/region/server.pb.cc
- c++/greptime/v1/region/server.pb.h
- java/src/main/java/greptime/v1/index/InvertedIndex.java
- java/src/main/java/io/greptime/v1/region/Server.java
- proto/greptime/v1/index/inverted_index.proto
> feat: introduce roaring bitmap to inverted index

- c++/greptime/v1/region/server.pb.cc
- c++/greptime/v1/region/server.pb.h
- java/src/main/java/io/greptime/v1/region/Server.java
- proto/greptime/v1/region/server.proto
- https://github.com/GreptimeTeam/greptimedb/issues/5803
Add bulk insert region server request type
> feat: add bulk insert request type

- .github/workflows/license.yaml
- .github/workflows/main.yml
- .github/workflows/semantic-pr.yml
> chore: upgrade ci runner image version

- build.rs
- c++/greptime/v1/region/server.pb.cc
- c++/greptime/v1/region/server.pb.h
- java/src/main/java/io/greptime/v1/region/Server.java
- proto/greptime/v1/region/server.proto
Refactor bulk insert request definition
> refactor: add selection to bulk

- c++/greptime/v1/region/server.pb.cc
- c++/greptime/v1/region/server.pb.h
- java/src/main/java/io/greptime/v1/region/Server.java
- proto/greptime/v1/region/server.proto
Add data header to `ArrowIpc` type bulk request so we can avoid a protobuf encode
> feat: data header to requests

- c++/greptime/v1/region/server.pb.cc
- c++/greptime/v1/region/server.pb.h
- java/src/main/java/io/greptime/v1/region/Server.java
- proto/greptime/v1/region/server.proto
- Add ListMetadataRequest to RegionRequest
- Add a field metadata in RegionResponse to store the json list of serialized RegionMetadata
> feat: Add ListMetadataRequest

- .github/workflows/main.yml
https://github.com/GreptimeTeam/greptime-proto/pull/254
This patch added protobuf format check.
> ci: add proto fmt check

- README.md
This repository was archived: https://github.com/GreptimeTeam/greptimedb-client-java
Use new repository:
- https://github.com/GreptimeTeam/greptimedb-ingester-java
- https://github.com/GreptimeTeam/greptimedb-ingester-rust
- https://github.com/GreptimeTeam/greptimedb-ingester-go
> fix(docs): fix sdk link
