- build.rs
- proto/greptime/v1/meta/lock.proto
- src/v1/meta.rs
This pr add a `lock.proto` for distributed lock.
https://github.com/GreptimeTeam/greptimedb/pull/961
> feat: add lock.proto

- proto/greptime/v1/meta/lock.proto
This pr mainly change:
1. fix typo.
2. rename "expire" -> "expire_secs".
https://github.com/GreptimeTeam/greptimedb/pull/961
> fix: typo and rename "expire" -> "expire_secs"

- src/v1/meta.rs
This pr main change: gen_set_header for BatchGetRequest
#7
> chore: gen_set_header for BatchGetRequest

- build.rs
- src/v1.rs
Add gRPC server reflection, suitable for debugging and illustrating purpose.
> feat: add gRPC reflection service

- src/v1/meta.rs
Add `gen_set_header` for `BatchDeleteRequest` 😂
> chore: add `gen_set_header` for `BatchDeleteRequest`

- src/v1/meta.rs
I had a problem with greptimedb:
When I set the header in the code, it will be overwritten in the meta client.
This pr mainly fix this problem.
> fix: set header for meta structs

- build.rs
Derive Serialize/Deserialize for SemanticType
> feat: impl serde for semantic type

- src/v1.rs
```
impl From<ValueData> for Value
```
> feat: from valuedata for value

- c++/greptime/v1/region/server.grpc.pb.cc
- c++/greptime/v1/region/server.grpc.pb.h
- c++/greptime/v1/region/server.pb.cc
- c++/greptime/v1/region/server.pb.h
- java/src/main/java/io/greptime/v1/region/Server.java
- proto/greptime/v1/region/server.proto
- rename `RegionServer` to `Region`, to avoid generating structs like `RegionServerServer` and `RegionServerService`
- rename `request` to `region_request_body`, to make it more distinguishable
> chore: rename RegionServer to Region

- Cargo.toml
- build.rs
- src/v1/region.rs
To make the request types to-string-able.
> feat: make region request derive strum

- proto/greptime/v1/region/server.proto
Documents that primary_key holds ids of columns.
> docs: update primary key comment

- c++/greptime/v1/region/server.pb.cc
- c++/greptime/v1/region/server.pb.h
- java/src/main/java/io/greptime/v1/region/Server.java
- proto/greptime/v1/region/server.proto
Open/Create request used to require a dir parameter for storing path. But this path is a relative path, it's then concat-ed to **the root path configured on datanode**. Since the logic of generating a relative path is neither defined in metasrv nor datanode/mito, I prefer to pass all the "raw material" required for a complete storage path, and let datanode handles them all.
The logic of generating storage path is in `src/table/src/engine.rs`:
```rust
pub fn region_dir(catalog_name: &str, schema_name: &str, region_id: RegionId) -> String {
format!(
"{}{}",
table_dir(catalog_name, schema_name, region_id.table_id()),
region_name(region_id.table_id(), region_id.region_number()) …
```
> feat: remove storage path in open/create request

- c++/CMakeLists.txt
Add a missing but required `CMakeLists.txt` file in the `c++` directory.
> fix: add a missing CMakeLists.txt file

- c++/greptime/v1/region/server.pb.cc
- c++/greptime/v1/region/server.pb.h
- java/src/main/java/io/greptime/v1/region/Server.java
- proto/greptime/v1/region/server.proto
This pr mainly adds `dbname` to region request header for tracing from frontend to datanode.
> chore: add `dbname` in region request header for tracking purpose

- .github/workflows/license.yaml
- .github/workflows/main.yml
- .github/workflows/pr-title-checker.yml
This PR downgrades container version to Ubuntu 20.04
> ci: downgrade container to ubuntu 20.04

- Cargo.toml
bump
- tonic: `0.10`
- tonic-build: `0.10`
- prost: `0.12`
> chore(deps): bump tonic, tonic-build and prost

- .github/workflows/mvn_publish.yml
- java/pom.xml
Add an action to publish java artifact to maven when releasing.
> ci: publish maven artifact

- java/pom.xml
Failed to execute old maven gpg plugin, see https://github.com/GreptimeTeam/greptime-proto/actions/runs/6732265535/job/18298632332
The latest gpg plugin runs fine: https://github.com/GreptimeTeam/greptime-proto/actions/runs/6732444618
> chore: upgrade maven gpg plugin

- c++/greptime/v1/region/server.pb.cc
- c++/greptime/v1/region/server.pb.h
- java/src/main/java/io/greptime/v1/region/Server.java
- proto/greptime/v1/region/server.proto
Given the various procedures may require different extended return values, this patch adds a flexible map to the return type of the region server
related to https://github.com/GreptimeTeam/greptimedb/issues/3513
> feat: add extension field to region response

- c++/greptime/v1/flow/server.pb.cc
- c++/greptime/v1/flow/server.pb.h
- java/src/main/java/io/greptime/v1/flow/Server.java
- proto/greptime/v1/flow/server.proto
refactor: replace `sink_table_id` with `sink_table_name`
> refactor: replace `sink_table_id` with `sink_table_name`

- c++/greptime/v1/region/server.pb.cc
- c++/greptime/v1/region/server.pb.h
- java/src/main/java/io/greptime/v1/region/Server.java
- proto/greptime/v1/region/server.proto
This refers to the issue "Pass query context down to region server service in Datanode".
https://github.com/GreptimeTeam/greptimedb/issues/3752
> feat: add QueryContext to RegionRequestHeader

- c++/greptime/v1/region/server.pb.cc
- c++/greptime/v1/region/server.pb.h
- java/src/main/java/io/greptime/v1/region/Server.java
- proto/greptime/v1/region/server.proto
Add compaction type parameters.
> chore: add compaction paramaters

- java/pom.xml
As the title said
- Summarize your change (**mandatory**)
- How does this PR work? Need a brief introduction for the changed logic (optional)
- Describe clearly one logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)
> feat: proto 0.7.0

- build.rs
> chore: derive every type with serde

- c++/greptime/v1/region/server.pb.cc
- c++/greptime/v1/region/server.pb.h
- java/src/main/java/io/greptime/v1/region/Server.java
- proto/greptime/v1/region/server.proto
This PR restores `RegionSelection` related messages in proto to avoid breaking main branch in DB.
> fix: restore region selection to avoid breaking main branch
